### ISSUE TITLE
Error in executing the playbook

### ISSUE THREAD

**Issue by pravingit** [mvelazc0/PurpleAD#1]
Hi @mvelazc0 

getting exception System IO error. Please find the attached error snapshot. 

Can you please help me to run the command. Or please suggest the steps to load the Purple sharp assembly. Do I need to import the Purple sharp project in Visual Studio and do some changes then run?

Please suggest..
![2023-02-11 18_35_25-Administrator_ Windows PowerShell](https://user-images.githubusercontent.com/37175598/218259755-a85e5485-fc0a-41f1-a760-fba1ce11f749.png)

**Comment by pravingit** [comment]
Please help me where I am doing mistake?

**Comment by pravingit** [comment]
![timeout error](https://user-images.githubusercontent.com/37175598/218260572-fa7d1014-0e0a-43fa-b984-aab3d2aca14c.png)
Please find the attache timeout error.

**Comment by mvelazc0** [comment]
Hi @pravingit ! 

The first error was because the user was not an administrative user on the remote host. 

The second error is because the service is not listening on the remote host. You will need to disable the Windows Firewall or create an exception for SMB and RPC ports.

**Comment by pravingit** [comment]
Thanks @mvelazc0  let me check .. Also just checking are we cover all the technique IDs of MITRE or can we add custom Techniques ID which was is not present in C# coding.

Can you please provide hints on how we can manually feed the technique ID which is not present in code.

**Comment by mvelazc0** [comment]
Hey @pravingit . Unfortunately, the way PurpleSharp is written now, you would have to add custom C# code. Ideally, you could add modules but this is not possible now.
